import { Nav } from "@/components/Nav";
import Particles from "@/components/particles";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <Particles className="absolute inset-0 -z-10 animate-fade-in" quantity={100} />
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
